#!/usr/bin/env php
<?php
/**
 * Copyright 2017 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Google\Cloud\Utils\Flex;

if (file_exists(__DIR__ . '/../../../vendor/autoload.php')) {
    // Run the command from the git clone.
    require_once __DIR__ . '/../../../vendor/autoload.php';
} else if (file_exists(__DIR__ . '/../../../../../../vendor/autoload.php')) {
    // Run the command from the vendor dir installation.
    require_once __DIR__ . '/../../../../../../vendor/autoload.php';
}

use Google\Cloud\Utils\Flex\FlexExecCommand;

use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new FlexExecCommand());
$app->run();
