name: Generate Reference Documentation

on:
    workflow_call:
        inputs:
            title:
                type: string
                default: "Reference Documentation"
                required: true
            tag:
                type: string
                description: "The version tag to use for the documentation. Uses current tag if empty."
            exclude:
                type: string
                description: "JSON array of directories to exclude from documentation"

permissions:
  contents: write

jobs:
    docs:
        name: "Generate and Deploy Documentation"
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
        - if: inputs.tag == ''
          id: getTag
          name: Get Tag
          run: |
            TAG=${GITHUB_REF#refs/*/}
            if [ -z "$TAG" ]; then
                echo "No tag found"
                exit 1
            fi
            echo ::set-output name=tag::$TAG
        - name: Download Doctum
          run: |
            curl -# https://doctum.long-term.support/releases/5.5/doctum.phar -o doctum.phar
            curl -# https://doctum.long-term.support/releases/5.5/doctum.phar.sha256  -o doctum.phar.sha256
            sha256sum --strict --check doctum.phar.sha256
        - name: Generate Doctum Config
          run: |
            DOCTUM_CONFIG=$(cat <<'EOF'
                <?php
                use Doctum\Doctum;
                use Symfony\Component\Finder\Finder;
                use Doctum\RemoteRepository\GitHubRemoteRepository;

                $iterator = Finder::create()
                    ->files()
                    ->name('*.php')
                    ->exclude('GPBMetadata')
                    ->exclude(json_decode(${{ inputs.exclude || '[]' }}. true))
                    ->in(__DIR__ . '/src');

                return new Doctum($iterator, [
                    'title'                => '${{ inputs.title }}',
                    'version'              => '${{ inputs.tag || steps.getTag.outputs.tag }}',
                    'build_dir'            => __DIR__ . '/.build/%version%',
                    'cache_dir'            => __DIR__ . '/.cache/%version%',
                    'remote_repository'    => new GitHubRemoteRepository('${{ github.repository }}', __DIR__),
                    'default_opened_level' => 1,
                ]);
            EOF
            )
            echo $DOCTUM_CONFIG; # for debugging
            echo $DOCTUM_CONFIG > doctum-config.php;
        - name: Run Doctum to Generate Documentation
          run: |
            php doctum.phar update doctum-config.php -v --ignore-parse-errors
        - name: Redirect Index to Latest Version
          run: |
            cat << EOF > .build/index.html
              <meta http-equiv='refresh' content='0;url=/${{github.event.repository.name}}/${{ inputs.tag || steps.getTag.outputs.tag }}'>
            EOF

        - run: |
            git submodule add -q -f -b gh-pages https://github.com/${{ github.repository }} .ghpages
            rsync -aP .build/* .ghpages/
        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: .ghpages
