name: Test Suite
on:
  push:
    branches:
      - main
  pull_request:

jobs:
    test:
        runs-on: ${{matrix.operating-system}}
        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php: [ "8.0", "8.1", "8.2", "8.3", "8.4" ]
        name: PHP ${{matrix.php }} Unit Test
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                extensions: zip
            - name: Install Dependencies
              uses: nick-invision/retry@v3
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: composer install
            - name: Set Test Bin Dir
              run: echo "$GITHUB_WORKSPACE/test/bin" >> $GITHUB_PATH
            - name: Run Script
              run: vendor/bin/phpunit

    code-standards:
        uses: ./.github/workflows/code-standards.yml
        with:
            path: src
            exclude-patterns: '["Fixers\/ClientUpgradeFixer\/examples"]'

    code-standards-with-config:
        uses: ./.github/workflows/code-standards.yml
        with:
            path: .
            config: .php-cs-fixer.default.php
            exclude-patterns: '["vendor", "test", "examples", "scripts"]'

    static-analysis:
        uses: ./.github/workflows/static-analysis.yml

    build_docs:
      uses: ./.github/workflows/doctum.yml
      with:
        title: "Google Cloud PHP Tools"
        default_version: ${{ github.head_ref || github.ref_name }}
        dry_run: true
